### PR TITLE
feat: add mosquitto image

### PR DESCRIPTION
**Pull request by fooker**
Adds image for mosquitto MQTT server.

### CODE REVIEW

**Review by IgorLaborieWefox — APPROVED** [review]
Notes that eventually, images will be moved to  companion crate (`rustainer-images`).

**Review by IgorLaborieWefox — CHANGES_REQUESTED** [review]
There are build issue that need to be fixed before merge

**Comment by fooker** [comment]
> There are build issue that need to be fixed before merge

Sorry about these. Should be fixed

**Review by IgorLaborieWefox — APPROVED** [review]

**Comment by IgorLaborieWefox** [comment]
Thank you for your contribution

**Pull request merged**
